### PR TITLE
fix: [#95] Fix file-loader configuration

### LINKED ISSUE #95: JS error on browser when running `npm run dev`
I get a JS error when running the dev server. 

```
Uncaught TypeError: this.path.indexOf is not a function
    at e.load (excalibur.min.js:8)
    at t (excalibur.min.js:8)
    at e.load (excalibur.min.js:8)
    at e.load (excalibur.min.js:8)
    at e.start (excalibur.min.js:8)
    at Object../src/main.ts (main.ts:32)
    at __webpack_require__ (bootstrap:19)
    at Object.0 (resources.ts:33)
    at __webpack_require__ (bootstrap:19)
    at bootstrap:83
```

### Steps to reproduce

1. Run `npm run dev`
2. Open the page `localhost:8080`
3. Observe the console

### Workaround

I checked with `git bisect` and the problem seems to be introduced by commit 8cc2fac.

_Downgrading file-loader 6.1.0 to 4.3.0 gets rid of the issue._

### Versions
- sample-platformer be1505f
- Excalibur 0.24.5
- file-loader 6.1.0
- Chrome 85
- node 12.18.3

### PR DESCRIPTION
**Pull request by apaatsio**
The default value for the esModule option had changed from false to true in file-loader v5. We need to use false here.

Closes #95

### CODE REVIEW

**Review by eonarheim — APPROVED** [review]
@apaatsio thanks for the fix!
